package com.hhxh.car.base.member.domain;

// default package
// Generated 2015-8-11 16:21:38 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import com.hhxh.car.base.carshop.domain.CarShop;
import com.hhxh.car.opr.domain.Order;

/**
 * BaseMemberId generated by hbm2java
 */
@Entity
@Table(name = "base_member")
public class Member implements java.io.Serializable
{
	@Id
	@Column
	private String id;
	@Column
	private String code;
	@Column
	private String cell ;
	@Column
	private String name;
	@Column
	private String simpleName;
	@Column
	private Integer userType;
	@Column
	private String MCARDNO;
	@Column
	private String MCARDURL;
	@Column
	private Date registerDate;
	@Column
	private String city;
	@Column
	private String IDCARDNO;
	@Column
	private String IDCARDURL;
	@Column
	private String VIN;
	@Column
	private Integer auditState;
	@Column
	private Integer useState;
	@Column
	private Date VIPtime;
	@Column
	private Integer VIPlevel;
	@Column
	private BigDecimal integration;
	@Column
	private String email;
	@Column
	private String qq;
	@Column
	private String weixin;
	@Column
	private String address;
	@Column
	private Date birthday;
	@Column
	private String folk;
	@Column
	private Integer gender;
	@Column
	private Integer merriageState;
	@Column
	private Date updateTime;
	@Column
	private String memo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shopID")
	private CarShop carShop;
	
	@OneToMany(mappedBy="worker",fetch=FetchType.LAZY)
	private Set<Order> orders = new HashSet<Order>();
	
	@OneToOne(fetch=FetchType.LAZY,mappedBy="")
	private WorkerBlackList workerBlackList ;

	public Member()
	{
	}

	public Member(String id)
	{
		this.id = id;
	}

	
	public String getId()
	{
		return id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getCode()
	{
		return code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getSimpleName()
	{
		return simpleName;
	}

	public void setSimpleName(String simpleName)
	{
		this.simpleName = simpleName;
	}

	public Integer getUserType()
	{
		return userType;
	}

	public void setUserType(Integer userType)
	{
		this.userType = userType;
	}

	public String getMCARDNO()
	{
		return MCARDNO;
	}

	public void setMCARDNO(String mCARDNO)
	{
		MCARDNO = mCARDNO;
	}

	public String getMCARDURL()
	{
		return MCARDURL;
	}

	public void setMCARDURL(String mCARDURL)
	{
		MCARDURL = mCARDURL;
	}

	public Date getRegisterDate()
	{
		return registerDate;
	}

	public void setRegisterDate(Date registerDate)
	{
		this.registerDate = registerDate;
	}

	public String getCity()
	{
		return city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	public String getIDCARDNO()
	{
		return IDCARDNO;
	}

	public void setIDCARDNO(String iDCARDNO)
	{
		IDCARDNO = iDCARDNO;
	}

	public String getIDCARDURL()
	{
		return IDCARDURL;
	}

	public void setIDCARDURL(String iDCARDURL)
	{
		IDCARDURL = iDCARDURL;
	}

	public String getVIN()
	{
		return VIN;
	}

	public void setVIN(String vIN)
	{
		VIN = vIN;
	}

	public Integer getAuditState()
	{
		return auditState;
	}

	public void setAuditState(Integer auditState)
	{
		this.auditState = auditState;
	}

	public Integer getUseState()
	{
		return useState;
	}

	public void setUseState(Integer useState)
	{
		this.useState = useState;
	}

	public Date getVIPtime()
	{
		return VIPtime;
	}

	public void setVIPtime(Date vIPtime)
	{
		VIPtime = vIPtime;
	}

	public Integer getVIPlevel()
	{
		return VIPlevel;
	}

	public void setVIPlevel(Integer vIPlevel)
	{
		VIPlevel = vIPlevel;
	}

	public BigDecimal getIntegration()
	{
		return this.integration;
	}

	public void setIntegration(BigDecimal integration)
	{
		this.integration = integration;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getQq()
	{
		return this.qq;
	}

	public void setQq(String qq)
	{
		this.qq = qq;
	}

	public String getWeixin()
	{
		return this.weixin;
	}

	public void setWeixin(String weixin)
	{
		this.weixin = weixin;
	}

	public String getAddress()
	{
		return this.address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	public Date getBirthday()
	{
		return this.birthday;
	}

	public void setBirthday(Date birthday)
	{
		this.birthday = birthday;
	}

	public String getFolk()
	{
		return this.folk;
	}

	public void setFolk(String folk)
	{
		this.folk = folk;
	}

	public Integer getGender()
	{
		return this.gender;
	}

	public void setGender(Integer gender)
	{
		this.gender = gender;
	}

	public Integer getMerriageState()
	{
		return this.merriageState;
	}

	public void setMerriageState(Integer merriageState)
	{
		this.merriageState = merriageState;
	}

	public Date getUpdateTime()
	{
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime)
	{
		this.updateTime = updateTime;
	}

	public String getMemo()
	{
		return this.memo;
	}

	public void setMemo(String memo)
	{
		this.memo = memo;
	}

	public CarShop getCarShop()
	{
		return carShop;
	}

	public void setCarShop(CarShop carShop)
	{
		this.carShop = carShop;
	}

	public String getCell()
	{
		return cell;
	}

	public void setCell(String cell)
	{
		this.cell = cell;
	}

	@Override
	public String toString()
	{
		return "Member [id=" + id + ", code=" + code + ", cell=" + cell + ", name=" + name + ", simpleName=" + simpleName + ", userType=" + userType + ", MCARDNO=" + MCARDNO + ", MCARDURL=" + MCARDURL + ", registerDate=" + registerDate + ", city=" + city + ", IDCARDNO=" + IDCARDNO + ", IDCARDURL=" + IDCARDURL + ", VIN=" + VIN + ", auditState=" + auditState + ", useState=" + useState + ", VIPtime=" + VIPtime + ", VIPlevel=" + VIPlevel + ", integration=" + integration + ", email=" + email + ", qq=" + qq + ", weixin=" + weixin + ", address=" + address + ", birthday=" + birthday + ", folk=" + folk + ", gender=" + gender + ", merriageState=" + merriageState + ", updateTime=" + updateTime + ", memo=" + memo + "]";
	}

	public Set<Order> getOrders()
	{
		return orders;
	}

	public void setOrders(Set<Order> orders)
	{
		this.orders = orders;
	}
	
}
