package com.hhxh.car.tig.domain;

// Generated 2015-8-6 15:46:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hhxh.car.permission.domain.User;

/**
 * OprAdvertisement generated by hbm2java
 */
@Entity
@Table(name="opr_advertisement")
public class Advertisement implements java.io.Serializable {

	@Id
	@Column
	private String id;
	@Column
	private String adverCode;
	@Column
	private String imgUrl;
	@Column
	private String filepath;
	@Column
	private String filename;
	@Column
	private String content;
	@Column
	private String serverIP;
	@Column
	private String port;
	@Column
	private Integer isEnable;
	@Column
	private Date createTime;
	@Column
	private String name;
	@Column
	private Integer adverType;
	@Column
	private String memo;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="creatorID")
	private User user ;

	public Advertisement() {
	}

	public Advertisement(String id) {
		this.id = id;
	}

	public Advertisement(String id, String adverCode, String imgUrl,
			String filepath, String filename, String content, String serverIp,
			String port, Integer isEnable, String creatorId, Date createTime,
			String name, Integer adverType, String memo) {
		this.id = id;
		this.adverCode = adverCode;
		this.imgUrl = imgUrl;
		this.filepath = filepath;
		this.filename = filename;
		this.content = content;
		this.serverIP = serverIp;
		this.port = port;
		this.isEnable = isEnable;
		this.createTime = createTime;
		this.name = name;
		this.adverType = adverType;
		this.memo = memo;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAdverCode() {
		return this.adverCode;
	}

	public void setAdverCode(String adverCode) {
		this.adverCode = adverCode;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getFilepath() {
		return this.filepath;
	}

	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}


	public String getServerIP() {
		return serverIP;
	}

	public void setServerIP(String serverIP) {
		this.serverIP = serverIP;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	public Integer getIsEnable() {
		return this.isEnable;
	}

	public void setIsEnable(Integer isEnable) {
		this.isEnable = isEnable;
	}


	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAdverType() {
		return this.adverType;
	}

	public void setAdverType(Integer adverType) {
		this.adverType = adverType;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Override
	public String toString() {
		return "Advertisement [id=" + id + ", adverCode=" + adverCode
				+ ", imgUrl=" + imgUrl + ", filepath=" + filepath
				+ ", filename=" + filename + ", content=" + content
				+ ", serverIP=" + serverIP + ", port=" + port + ", isEnable="
				+ isEnable + ", createTime=" + createTime + ", name=" + name
				+ ", adverType=" + adverType + ", memo=" + memo + "]";
	}

	
}
