package com.hhxh.car.tig.domain;

// Generated 2015-8-14 9:25:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hhxh.car.permission.domain.User;

/**
 * TAppCase generated by hbm2java
 */
@Entity
@Table(name="t_app_case")
public class AppCase implements java.io.Serializable
{

	@Id
	@Column
	private String id;
	@Column
	private String appName;
	@Column
	private String sortCode;
	@Column
	private String appDes;
	@Column
	private Integer appLevel;
	@Column
	private BigDecimal appAmount;
	@Column
	private String downLoadUrl;
	@Column
	private String logoUrl;
	@Column
	private Integer isUse;
	@Column
	private Integer downNum;
	@Column
	private String updateInfo;
	@Column
	private BigDecimal versionCode;
	@Column
	private String versionName;
	@Column
	private Date uploadTime;
	@Column
	private String filePath;
	@Column
	private String fileName;

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="creatorId")
	private User user ;
	
	public AppCase()
	{
	}

	public AppCase(String id)
	{
		this.id = id;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getAppName()
	{
		return this.appName;
	}

	public void setAppName(String appName)
	{
		this.appName = appName;
	}

	public String getSortCode()
	{
		return this.sortCode;
	}

	public void setSortCode(String sortCode)
	{
		this.sortCode = sortCode;
	}

	public String getAppDes()
	{
		return this.appDes;
	}

	public void setAppDes(String appDes)
	{
		this.appDes = appDes;
	}

	public Integer getAppLevel()
	{
		return this.appLevel;
	}

	public void setAppLevel(Integer appLevel)
	{
		this.appLevel = appLevel;
	}

	public BigDecimal getAppAmount()
	{
		return this.appAmount;
	}

	public void setAppAmount(BigDecimal appAmount)
	{
		this.appAmount = appAmount;
	}

	public String getDownLoadUrl()
	{
		return this.downLoadUrl;
	}

	public void setDownLoadUrl(String downLoadUrl)
	{
		this.downLoadUrl = downLoadUrl;
	}

	public String getLogoUrl()
	{
		return this.logoUrl;
	}

	public void setLogoUrl(String logoUrl)
	{
		this.logoUrl = logoUrl;
	}

	public Integer getIsUse()
	{
		return this.isUse;
	}

	public void setIsUse(Integer isUse)
	{
		this.isUse = isUse;
	}

	public Integer getDownNum()
	{
		return this.downNum;
	}

	public void setDownNum(Integer downNum)
	{
		this.downNum = downNum;
	}

	public String getUpdateInfo()
	{
		return this.updateInfo;
	}

	public void setUpdateInfo(String updateInfo)
	{
		this.updateInfo = updateInfo;
	}

	public BigDecimal getVersionCode()
	{
		return this.versionCode;
	}

	public void setVersionCode(BigDecimal versionCode)
	{
		this.versionCode = versionCode;
	}

	public String getVersionName()
	{
		return this.versionName;
	}

	public void setVersionName(String versionName)
	{
		this.versionName = versionName;
	}

	public Date getUploadTime()
	{
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime)
	{
		this.uploadTime = uploadTime;
	}

	public String getFilePath()
	{
		return this.filePath;
	}

	public void setFilePath(String filePath)
	{
		this.filePath = filePath;
	}

	public String getFileName()
	{
		return this.fileName;
	}

	public void setFileName(String fileName)
	{
		this.fileName = fileName;
	}

	public User getUser()
	{
		return user;
	}

	public void setUser(User user)
	{
		this.user = user;
	}

	@Override
	public String toString()
	{
		return "AppCase [id=" + id + ", appName=" + appName + ", sortCode=" + sortCode + ", appDes=" + appDes + ", appLevel=" + appLevel + ", appAmount=" + appAmount + ", downLoadUrl=" + downLoadUrl
				+ ", logoUrl=" + logoUrl + ", isUse=" + isUse + ", downNum=" + downNum + ", updateInfo=" + updateInfo + ", versionCode=" + versionCode + ", versionName=" + versionName
				+ ", uploadTime=" + uploadTime + ", filePath=" + filePath + ", fileName=" + fileName + "]";
	}

}
