package com.hhxh.car.tig.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


// Generated 2015-9-7 9:40:52 by Hibernate Tools 3.4.0.CR1

/**
 * TigPushMessagePart generated by hbm2java
 */
@Entity
@Table(name="tig_push_message_part")
public class PushMessagePart implements java.io.Serializable
{
	@Id
	@Column
	private String id;
	@Column
	private String msgId;
	@Column
	private Integer deviceType ;
	@Column
	private Integer sendStatus ;
	@Column
	private String sendErrorMessage ;
	@Column
	private String sendErrorCode ;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="parentId")
	private PushMessage pushMessage ;
	

	public PushMessagePart()
	{
	}

	public PushMessagePart(String id)
	{
		this.id = id;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getMsgId()
	{
		return this.msgId;
	}

	public void setMsgId(String msgId)
	{
		this.msgId = msgId;
	}

	public PushMessage getPushMessage()
	{
		return pushMessage;
	}

	public void setPushMessage(PushMessage pushMessage)
	{
		this.pushMessage = pushMessage;
	}

	public Integer getDeviceType()
	{
		return deviceType;
	}

	public void setDeviceType(Integer deviceType)
	{
		this.deviceType = deviceType;
	}

	public Integer getSendStatus()
	{
		return sendStatus;
	}

	public void setSendStatus(Integer sendStatus)
	{
		this.sendStatus = sendStatus;
	}

	public String getSendErrorMessage()
	{
		return sendErrorMessage;
	}

	public void setSendErrorMessage(String sendErrorMessage)
	{
		this.sendErrorMessage = sendErrorMessage;
	}

	public String getSendErrorCode()
	{
		return sendErrorCode;
	}

	public void setSendErrorCode(String sendErrorCode)
	{
		this.sendErrorCode = sendErrorCode;
	}
	
}
