package com.hhxh.car.tig.domain;

// Generated 2015-9-6 17:33:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.hhxh.car.permission.domain.User;

/**
 * TigPushMessage generated by hbm2java
 */
@Entity
@Table(name="tig_push_message")
public class PushMessage implements java.io.Serializable
{

	@Id
	@Column(name="fid")
	private String id;
	@Column
	private Integer fmessageType;
	@Column
	private String fpermid;
	@Column
	private String fcontent;
	@Column
	private Date fcreateDate;
	@Column
	private String ftitle;
	@Column
	private Integer fexpiresTime;
	@Column
	private Date fsendTime;
	@Column
	private Integer fdeviceType;
	
	@OneToMany(fetch=FetchType.LAZY,mappedBy="pushMessage")
	private Set<PushMessagePart> pushMessageParts = new HashSet<PushMessagePart>();
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="fcreatorId")
	private User createUser ;

	public PushMessage()
	{
	}

	public PushMessage(String id)
	{
		super();
		this.id = id;
	}

	public String getId()
	{
		return id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public Integer getFmessageType()
	{
		return this.fmessageType;
	}

	public void setFmessageType(Integer fmessageType)
	{
		this.fmessageType = fmessageType;
	}

	public String getFpermid()
	{
		return this.fpermid;
	}

	public void setFpermid(String fpermid)
	{
		this.fpermid = fpermid;
	}

	public String getFcontent()
	{
		return this.fcontent;
	}

	public void setFcontent(String fcontent)
	{
		this.fcontent = fcontent;
	}


	public Date getFcreateDate()
	{
		return this.fcreateDate;
	}

	public void setFcreateDate(Date fcreateDate)
	{
		this.fcreateDate = fcreateDate;
	}

	public String getFtitle()
	{
		return this.ftitle;
	}

	public void setFtitle(String ftitle)
	{
		this.ftitle = ftitle;
	}

	public Integer getFexpiresTime()
	{
		return this.fexpiresTime;
	}

	public void setFexpiresTime(Integer fexpiresTime)
	{
		this.fexpiresTime = fexpiresTime;
	}

	public Date getFsendTime()
	{
		return this.fsendTime;
	}

	public void setFsendTime(Date fsendTime)
	{
		this.fsendTime = fsendTime;
	}

	public Integer getFdeviceType()
	{
		return this.fdeviceType;
	}

	public void setFdeviceType(Integer fdeviceType)
	{
		this.fdeviceType = fdeviceType;
	}

	@Override
	public String toString()
	{
		return "PushMessage [id=" + id + ", fmessageType=" + fmessageType + ", fpermid=" + fpermid + ", fcontent=" + fcontent + ", fcreatorId="  + ", fcreateDate=" + fcreateDate
				+ ", ftitle=" + ftitle + ", fexpiresTime=" + fexpiresTime + ", fsendTime=" + fsendTime + ", fdeviceType=" + fdeviceType + "]";
	}

	public Set<PushMessagePart> getPushMessageParts()
	{
		return pushMessageParts;
	}

	public void setPushMessageParts(Set<PushMessagePart> pushMessageParts)
	{
		this.pushMessageParts = pushMessageParts;
	}

	public User getCreateUser()
	{
		return createUser;
	}

	public void setCreateUser(User createUser)
	{
		this.createUser = createUser;
	}

}
