package com.hhxh.car.tig.domain;
// Generated 2015-8-12 11:49:18 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.hhxh.car.opr.order.domain.Order;

/**
 * TigUsers generated by hbm2java
 */
@Entity
@Table(name="tig_users")
public class TigUsers  implements java.io.Serializable {

	@Id
	@Column(name="user_id")
     private String id;
	@Column
     private String user_account;
	@Column
	private String user_pw;
	
	@OneToMany(mappedBy="tigUsers",fetch=FetchType.LAZY)
	private Set<Order> orders = new HashSet<Order>();

	@Column
	private String mySign;
	
     private String personId;
     private String headUrl;
     private Date accCreateTime;
     private Date lastLogin;
     private Date lastLogout;
     private Integer onlineStatus;
     private Integer failedLogins;
     private Integer isSystemUser;
     private Integer userType;
     private Integer isForbidden;
     private String mobile;
     private Integer isInvite;
     private Integer isActivate;
     private BigDecimal mapX;
     private BigDecimal mapY;
     private Long perfection;
     private Long credibility;
     private Date inviteDate;
     private String inviteCode;

    public TigUsers() {
    }

	
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }
    public Date getAccCreateTime() {
        return this.accCreateTime;
    }
    
    public void setAccCreateTime(Date accCreateTime) {
        this.accCreateTime = accCreateTime;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Date getLastLogout() {
        return this.lastLogout;
    }
    
    public void setLastLogout(Date lastLogout) {
        this.lastLogout = lastLogout;
    }
    public Integer getOnlineStatus() {
        return this.onlineStatus;
    }
    
    public void setOnlineStatus(Integer onlineStatus) {
        this.onlineStatus = onlineStatus;
    }
    public Integer getFailedLogins() {
        return this.failedLogins;
    }
    
    public void setFailedLogins(Integer failedLogins) {
        this.failedLogins = failedLogins;
    }
    public String getMySign() {
        return this.mySign;
    }
    
    public void setMySign(String mySign) {
        this.mySign = mySign;
    }
    public Integer getIsSystemUser() {
        return this.isSystemUser;
    }
    
    public void setIsSystemUser(Integer isSystemUser) {
        this.isSystemUser = isSystemUser;
    }
    public Integer getUserType() {
        return this.userType;
    }
    
    public void setUserType(Integer userType) {
        this.userType = userType;
    }
    public Integer getIsForbidden() {
        return this.isForbidden;
    }
    
    public void setIsForbidden(Integer isForbidden) {
        this.isForbidden = isForbidden;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public Integer getIsInvite() {
        return this.isInvite;
    }
    
    public void setIsInvite(Integer isInvite) {
        this.isInvite = isInvite;
    }
    public Integer getIsActivate() {
        return this.isActivate;
    }
    
    public void setIsActivate(Integer isActivate) {
        this.isActivate = isActivate;
    }
    public BigDecimal getMapX() {
        return this.mapX;
    }
    
    public void setMapX(BigDecimal mapX) {
        this.mapX = mapX;
    }
    public BigDecimal getMapY() {
        return this.mapY;
    }
    
    public void setMapY(BigDecimal mapY) {
        this.mapY = mapY;
    }
    public Long getPerfection() {
        return this.perfection;
    }
    
    public void setPerfection(Long perfection) {
        this.perfection = perfection;
    }
    public Long getCredibility() {
        return this.credibility;
    }
    
    public void setCredibility(Long credibility) {
        this.credibility = credibility;
    }
    public Date getInviteDate() {
        return this.inviteDate;
    }
    
    public void setInviteDate(Date inviteDate) {
        this.inviteDate = inviteDate;
    }
    public String getInviteCode() {
        return this.inviteCode;
    }
    
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }


	public String getId()
	{
		return id;
	}


	public void setId(String id)
	{
		this.id = id;
	}


	public String getUser_account()
	{
		return user_account;
	}


	public void setUser_account(String user_account)
	{
		this.user_account = user_account;
	}


	public String getUser_pw()
	{
		return user_pw;
	}


	public void setUser_pw(String user_pw)
	{
		this.user_pw = user_pw;
	}


	public Set<Order> getOrders()
	{
		return orders;
	}


	public void setOrders(Set<Order> orders)
	{
		this.orders = orders;
	}


}


