package com.hhxh.car.tig.domain;
// Generated 2015-8-12 11:49:18 by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.hhxh.car.opr.order.domain.Order;

/**
 * TigUsers generated by hbm2java
 */
@Entity
@Table(name="tig_users")
public class TigUsers  implements java.io.Serializable {

	@Id
	@Column(name="user_id")
     private String id;
	@Column
     private String user_account;
	@Column
	private String user_pw;
	
	@OneToMany(mappedBy="tigUsers",fetch=FetchType.LAZY)
	private Set<Order> orders = new HashSet<Order>();

	@Column
	private String mySign;
	
	@Column
     private String personId;
	@Column
     private String headUrl;
	@Column
     private Date acc_create_time;
	@Column
     private Date last_login;
	@Column
     private Date last_logout;
	@Column
     private Integer online_status;
	@Column
     private Integer failed_logins;
	@Column
     private Integer isSystemUser;
	@Column
     private Integer userType;
     @Column
     private Integer isForbidden;
     @Column
     private String FMobile;
     @Column
     private Integer isInvite;
     @Column
     private Integer isActivate;
     @Column
     private BigDecimal mapX;
     @Column
     private BigDecimal mapY;
     @Column
     private Long perfection;
     @Column
     private Long credibility;
     @Column
     private Date inviteDate;
     @Column
     private String inviteCode;

    public TigUsers() {
    }

	
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }
    
    public void setIsInvite(Integer isInvite) {
        this.isInvite = isInvite;
    }
    public Integer getIsActivate() {
        return this.isActivate;
    }
    
    public void setIsActivate(Integer isActivate) {
        this.isActivate = isActivate;
    }
    public BigDecimal getMapX() {
        return this.mapX;
    }
    
    public void setMapX(BigDecimal mapX) {
        this.mapX = mapX;
    }
    public BigDecimal getMapY() {
        return this.mapY;
    }
    
    public void setMapY(BigDecimal mapY) {
        this.mapY = mapY;
    }
    public Long getPerfection() {
        return this.perfection;
    }
    
    public void setPerfection(Long perfection) {
        this.perfection = perfection;
    }
    public Long getCredibility() {
        return this.credibility;
    }
    
    public void setCredibility(Long credibility) {
        this.credibility = credibility;
    }
    public Date getInviteDate() {
        return this.inviteDate;
    }
    
    public void setInviteDate(Date inviteDate) {
        this.inviteDate = inviteDate;
    }
    public String getInviteCode() {
        return this.inviteCode;
    }
    
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }


	public String getId()
	{
		return id;
	}


	public void setId(String id)
	{
		this.id = id;
	}


	public String getMySign()
	{
		return mySign;
	}


	public void setMySign(String mySign)
	{
		this.mySign = mySign;
	}


	public String getHeadUrl()
	{
		return headUrl;
	}


	public void setHeadUrl(String headUrl)
	{
		this.headUrl = headUrl;
	}


	public Date getAcc_create_time()
	{
		return acc_create_time;
	}


	public void setAcc_create_time(Date acc_create_time)
	{
		this.acc_create_time = acc_create_time;
	}


	public Date getLast_login()
	{
		return last_login;
	}


	public void setLast_login(Date last_login)
	{
		this.last_login = last_login;
	}


	public Date getLast_logout()
	{
		return last_logout;
	}


	public void setLast_logout(Date last_logout)
	{
		this.last_logout = last_logout;
	}


	public Integer getOnline_status()
	{
		return online_status;
	}


	public void setOnline_status(Integer online_status)
	{
		this.online_status = online_status;
	}


	public Integer getFailed_logins()
	{
		return failed_logins;
	}


	public void setFailed_logins(Integer failed_logins)
	{
		this.failed_logins = failed_logins;
	}


	public Integer getIsSystemUser()
	{
		return isSystemUser;
	}


	public void setIsSystemUser(Integer isSystemUser)
	{
		this.isSystemUser = isSystemUser;
	}


	public Integer getUserType()
	{
		return userType;
	}


	public void setUserType(Integer userType)
	{
		this.userType = userType;
	}


	public Integer getIsForbidden()
	{
		return isForbidden;
	}


	public void setIsForbidden(Integer isForbidden)
	{
		this.isForbidden = isForbidden;
	}


	public String getFMobile()
	{
		return FMobile;
	}


	public void setFMobile(String fMobile)
	{
		FMobile = fMobile;
	}


	public Integer getIsInvite()
	{
		return isInvite;
	}


	public String getUser_account()
	{
		return user_account;
	}


	public void setUser_account(String user_account)
	{
		this.user_account = user_account;
	}


	public String getUser_pw()
	{
		return user_pw;
	}


	public void setUser_pw(String user_pw)
	{
		this.user_pw = user_pw;
	}


	public Set<Order> getOrders()
	{
		return orders;
	}


	public void setOrders(Set<Order> orders)
	{
		this.orders = orders;
	}


}


