package com.hhxh.car.tig.domain;

// Generated 2015-7-22 17:36:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUpdateVersion generated by hbm2java
 */
@Entity
@Table(name="t_update_version")
public class UpdateVersion implements java.io.Serializable {

	@Id
	private String id;
	@Column
	private String updateInfo;
	@Column
	private Double versionCode;
	@Column
	private String downLoadUrl;
	@Column
	private Integer phoneType;
	@Column
	private String versionName;
	@Column
	private Date uploadTime;
	@Column
	private String creatorId;
	@Column
	private Date creatTime;
	@Column
	private String filePath;
	@Column
	private String fileName;

	public UpdateVersion() {
	}

	public UpdateVersion(String id) {
		this.id = id;
	}

	public UpdateVersion(String id, String updateInfo, Double versionCode,
			String downLoadUrl, Integer phoneType, String versionName,
			Date uploadTime, String creatorId, Date creatTime, String filePath,
			String fileName) {
		this.id = id;
		this.updateInfo = updateInfo;
		this.versionCode = versionCode;
		this.downLoadUrl = downLoadUrl;
		this.phoneType = phoneType;
		this.versionName = versionName;
		this.uploadTime = uploadTime;
		this.creatorId = creatorId;
		this.creatTime = creatTime;
		this.filePath = filePath;
		this.fileName = fileName;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUpdateInfo() {
		return this.updateInfo;
	}

	public void setUpdateInfo(String updateInfo) {
		this.updateInfo = updateInfo;
	}

	public Double getVersionCode() {
		return this.versionCode;
	}

	public void setVersionCode(Double versionCode) {
		this.versionCode = versionCode;
	}

	public String getDownLoadUrl() {
		return this.downLoadUrl;
	}

	public void setDownLoadUrl(String downLoadUrl) {
		this.downLoadUrl = downLoadUrl;
	}

	public Integer getPhoneType() {
		return this.phoneType;
	}

	public void setPhoneType(Integer phoneType) {
		this.phoneType = phoneType;
	}

	public String getVersionName() {
		return this.versionName;
	}

	public void setVersionName(String versionName) {
		this.versionName = versionName;
	}

	public Date getUploadTime() {
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime) {
		this.uploadTime = uploadTime;
	}

	public String getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId;
	}

	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Override
	public String toString() {
		return "UpdateVersion [id=" + id + ", updateInfo=" + updateInfo
				+ ", versionCode=" + versionCode + ", downLoadUrl="
				+ downLoadUrl + ", phoneType=" + phoneType + ", versionName="
				+ versionName + ", uploadTime=" + uploadTime + ", creatorId="
				+ creatorId + ", creatTime=" + creatTime + ", filePath="
				+ filePath + ", fileName=" + fileName + "]";
	}
	
	

}
