package com.hhxh.car.opr.order.domain;

// Generated 2015-8-12 11:36:29 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.hhxh.car.base.carshop.domain.CarShop;
import com.hhxh.car.base.member.domain.Member;
import com.hhxh.car.tig.domain.TigUsers;

/**
 * OprOrder generated by hbm2java
 */
@Entity
@Table(name="opr_order")
public class Order implements java.io.Serializable
{
	@Id
	@Column(name="orderCode")
	private String id;
	@Column
	private String orderName;
	@Column
	private String payOrderCode;
	@Column
	private Date orderTime;
	@Column
	private Date expectTime;
	@Column
	private Integer serviceType;
	@Column
	private Integer orderState;
	@Column
	private Integer orderNum;
	@Column
	private BigDecimal totalAmount;
	@Column
	private Integer payType;
	@Column
	private Integer payState;
	@Column
	private Integer busType;
	@Column
	private BigDecimal takeFare;
	@Column
	private BigDecimal sendFare;
	@Column
	private Date endTime;
	@Column
	private Date updateTime;
	@Column
	private Integer dealType;
	@Column
	private String memo;

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="carOwnerID")
	private TigUsers tigUsers ;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="shopID")
	private CarShop carShop ;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="workerID")
	private Member worker ;
	
	@OneToMany(fetch=FetchType.LAZY,mappedBy="order")
	private Set<OrderTrack> orderTracks = new HashSet<OrderTrack>();
	
	public Order()
	{
	}

	public Order(String id)
	{
		this.id = id ;
	}

	public String getOrderName()
	{
		return this.orderName;
	}

	public void setOrderName(String orderName)
	{
		this.orderName = orderName;
	}

	public String getPayOrderCode()
	{
		return this.payOrderCode;
	}

	public void setPayOrderCode(String payOrderCode)
	{
		this.payOrderCode = payOrderCode;
	}


	public Date getOrderTime()
	{
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime)
	{
		this.orderTime = orderTime;
	}

	public Date getExpectTime()
	{
		return this.expectTime;
	}

	public void setExpectTime(Date expectTime)
	{
		this.expectTime = expectTime;
	}

	public Integer getServiceType()
	{
		return this.serviceType;
	}

	public void setServiceType(Integer serviceType)
	{
		this.serviceType = serviceType;
	}

	public Integer getOrderState()
	{
		return this.orderState;
	}

	public void setOrderState(Integer orderState)
	{
		this.orderState = orderState;
	}

	public Integer getOrderNum()
	{
		return this.orderNum;
	}

	public void setOrderNum(Integer orderNum)
	{
		this.orderNum = orderNum;
	}

	public BigDecimal getTotalAmount()
	{
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount)
	{
		this.totalAmount = totalAmount;
	}

	public Integer getPayType()
	{
		return this.payType;
	}

	public void setPayType(Integer payType)
	{
		this.payType = payType;
	}

	public Integer getPayState()
	{
		return this.payState;
	}

	public void setPayState(Integer payState)
	{
		this.payState = payState;
	}

	public Integer getBusType()
	{
		return this.busType;
	}

	public void setBusType(Integer busType)
	{
		this.busType = busType;
	}

	public BigDecimal getTakeFare()
	{
		return this.takeFare;
	}

	public void setTakeFare(BigDecimal takeFare)
	{
		this.takeFare = takeFare;
	}

	public BigDecimal getSendFare()
	{
		return this.sendFare;
	}

	public void setSendFare(BigDecimal sendFare)
	{
		this.sendFare = sendFare;
	}

	public Date getEndTime()
	{
		return this.endTime;
	}

	public void setEndTime(Date endTime)
	{
		this.endTime = endTime;
	}

	public Date getUpdateTime()
	{
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime)
	{
		this.updateTime = updateTime;
	}

	public Integer getDealType()
	{
		return this.dealType;
	}

	public void setDealType(Integer dealType)
	{
		this.dealType = dealType;
	}

	public String getMemo()
	{
		return this.memo;
	}

	public void setMemo(String memo)
	{
		this.memo = memo;
	}

	public String getId()
	{
		return id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public TigUsers getTigUsers()
	{
		return tigUsers;
	}

	public void setTigUsers(TigUsers tigUsers)
	{
		this.tigUsers = tigUsers;
	}

	public CarShop getCarShop()
	{
		return carShop;
	}

	public void setCarShop(CarShop carShop)
	{
		this.carShop = carShop;
	}

	public Member getWorker()
	{
		return worker;
	}

	public void setWorker(Member worker)
	{
		this.worker = worker;
	}

	@Override
	public String toString()
	{
		return "Order [id=" + id + ", orderName=" + orderName + ", payOrderCode=" + payOrderCode + ", orderTime=" + orderTime + ", expectTime=" + expectTime + ", serviceType=" + serviceType
				+ ", orderState=" + orderState + ", orderNum=" + orderNum + ", totalAmount=" + totalAmount + ", payType=" + payType + ", payState=" + payState + ", busType=" + busType + ", takeFare="
				+ takeFare + ", sendFare=" + sendFare + ", endTime=" + endTime + ", updateTime=" + updateTime + ", dealType=" + dealType + ", memo=" + memo + "]";
	}

	public Set<OrderTrack> getOrderTracks()
	{
		return orderTracks;
	}

	public void setOrderTracks(Set<OrderTrack> orderTracks)
	{
		this.orderTracks = orderTracks;
	}
	
	
	
}
