package com.hhxh.car.base.autopart.domain;

// Generated 2015-7-9 16:20:50 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.hhxh.car.base.busatom.domain.BusAtom;

/**
 * BaseAutoPartId generated by hbm2java
 */
@Entity
@Table(name="base_auto_part")
public class AutoPart implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	 
	@Id
	private String id;
	@Column
	private String partCode;
	@Column
	private String partName;
	@Column
	private String brandName;
	@Column
	private String spec;
	@Column
	private String model;
	@Column
	private BigDecimal sunitPrice;
	@Column
	private BigDecimal eunitPrice;
	@Column
	private BigDecimal yunitPrice;
	@Column
	private Integer useState;
	@Column
	private Integer isActivity;
	@Column
	private BigDecimal stock;
	@Column
	private Date updateTime;
	@Column
	private String partSource;
	@Column
	private String memo;
	
//	@OneToMany(mappedBy="autoPart")
//	private Set<BusAtom> busAtoms ;

	public AutoPart() {
	}

	public AutoPart(String id){
		this.id = id ;
	}
	
	public AutoPart(int isActivity) {
		this.isActivity = isActivity;
	}

	public AutoPart(String id, String partCode, String partName,
			String brandName, String spec, String model, BigDecimal sunitPrice,
			BigDecimal eunitPrice, BigDecimal yunitPrice, Integer useState,
			Integer isActivity, BigDecimal stock, Date updateTime,
			String partSource, String memo) {
		
		this.id = id;
		this.partCode = partCode;
		this.partName = partName;
		this.brandName = brandName;
		this.spec = spec;
		this.model = model;
		this.sunitPrice = sunitPrice;
		this.eunitPrice = eunitPrice;
		this.yunitPrice = yunitPrice;
		this.useState = useState;
		this.isActivity = isActivity;
		this.stock = stock;
		this.updateTime = updateTime;
		this.partSource = partSource;
		this.memo = memo;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPartCode() {
		return this.partCode;
	}

	public void setPartCode(String partCode) {
		this.partCode = partCode;
	}

	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public BigDecimal getSunitPrice() {
		return this.sunitPrice;
	}

	public void setSunitPrice(BigDecimal sunitPrice) {
		this.sunitPrice = sunitPrice;
	}

	public BigDecimal getEunitPrice() {
		return this.eunitPrice;
	}

	public void setEunitPrice(BigDecimal eunitPrice) {
		this.eunitPrice = eunitPrice;
	}

	public BigDecimal getYunitPrice() {
		return this.yunitPrice;
	}

	public void setYunitPrice(BigDecimal yunitPrice) {
		this.yunitPrice = yunitPrice;
	}

	public Integer getUseState() {
		return this.useState;
	}

	public void setUseState(Integer useState) {
		this.useState = useState;
	}

	public Integer getIsActivity() {
		return this.isActivity;
	}

	public void setIsActivity(Integer isActivity) {
		this.isActivity = isActivity;
	}

	public BigDecimal getStock() {
		return this.stock;
	}

	public void setStock(BigDecimal stock) {
		this.stock = stock;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getPartSource() {
		return this.partSource;
	}

	public void setPartSource(String partSource) {
		this.partSource = partSource;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	
	
//	public Set<BusAtom> getBusAtoms() {
//		return busAtoms;
//	}
//
//	public void setBusAtoms(Set<BusAtom> busAtoms) {
//		this.busAtoms = busAtoms;
//	}

	@Override
	public String toString() {
		return "AutoPart [id=" + id + ", partCode=" + partCode + ", partName="
				+ partName + ", brandName=" + brandName + ", spec=" + spec
				+ ", model=" + model + ", sunitPrice=" + sunitPrice
				+ ", eunitPrice=" + eunitPrice + ", yunitPrice=" + yunitPrice
				+ ", useState=" + useState + ", isActivity=" + isActivity
				+ ", stock=" + stock + ", updateTime=" + updateTime
				+ ", partSource=" + partSource + ", memo=" + memo + "]";
	}

	
}
