package com.zw.test.domain.com.domain;

// Generated 2015-8-14 9:25:10 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TAppCase generated by hbm2java
 */
public class AppCase implements java.io.Serializable
{

	private String id;
	private String appName;
	private String sortCode;
	private String appDes;
	private Integer appLevel;
	private BigDecimal appAmount;
	private String downLoadUrl;
	private String logoUrl;
	private Integer isUse;
	private Integer downNum;
	private String updateInfo;
	private BigDecimal versionCode;
	private String versionName;
	private Date uploadTime;
	private String creatorId;
	private String filePath;
	private String fileName;

	public AppCase()
	{
	}

	public AppCase(String id)
	{
		this.id = id;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getAppName()
	{
		return this.appName;
	}

	public void setAppName(String appName)
	{
		this.appName = appName;
	}

	public String getSortCode()
	{
		return this.sortCode;
	}

	public void setSortCode(String sortCode)
	{
		this.sortCode = sortCode;
	}

	public String getAppDes()
	{
		return this.appDes;
	}

	public void setAppDes(String appDes)
	{
		this.appDes = appDes;
	}

	public Integer getAppLevel()
	{
		return this.appLevel;
	}

	public void setAppLevel(Integer appLevel)
	{
		this.appLevel = appLevel;
	}

	public BigDecimal getAppAmount()
	{
		return this.appAmount;
	}

	public void setAppAmount(BigDecimal appAmount)
	{
		this.appAmount = appAmount;
	}

	public String getDownLoadUrl()
	{
		return this.downLoadUrl;
	}

	public void setDownLoadUrl(String downLoadUrl)
	{
		this.downLoadUrl = downLoadUrl;
	}

	public String getLogoUrl()
	{
		return this.logoUrl;
	}

	public void setLogoUrl(String logoUrl)
	{
		this.logoUrl = logoUrl;
	}

	public Integer getIsUse()
	{
		return this.isUse;
	}

	public void setIsUse(Integer isUse)
	{
		this.isUse = isUse;
	}

	public Integer getDownNum()
	{
		return this.downNum;
	}

	public void setDownNum(Integer downNum)
	{
		this.downNum = downNum;
	}

	public String getUpdateInfo()
	{
		return this.updateInfo;
	}

	public void setUpdateInfo(String updateInfo)
	{
		this.updateInfo = updateInfo;
	}

	public BigDecimal getVersionCode()
	{
		return this.versionCode;
	}

	public void setVersionCode(BigDecimal versionCode)
	{
		this.versionCode = versionCode;
	}

	public String getVersionName()
	{
		return this.versionName;
	}

	public void setVersionName(String versionName)
	{
		this.versionName = versionName;
	}

	public Date getUploadTime()
	{
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime)
	{
		this.uploadTime = uploadTime;
	}

	public String getCreatorId()
	{
		return this.creatorId;
	}

	public void setCreatorId(String creatorId)
	{
		this.creatorId = creatorId;
	}

	public String getFilePath()
	{
		return this.filePath;
	}

	public void setFilePath(String filePath)
	{
		this.filePath = filePath;
	}

	public String getFileName()
	{
		return this.fileName;
	}

	public void setFileName(String fileName)
	{
		this.fileName = fileName;
	}

}
