package com.hhxh.car.opr.domain;

// Generated 2015-8-17 10:19:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hhxh.car.permission.domain.User;
import com.hhxh.car.tig.domain.TigUsers;

/**
 * OprComplain generated by hbm2java
 */
@Entity
@Table(name="opr_complain")
public class Complain implements java.io.Serializable
{
	@Id
	@Column
	private String id;
	@Column
	private String objId;
	@Column
	private Integer objType;
	@Column
	private String objName;
	@Column
	private Date complainTime;
	@Column
	private String complainReason;
	@Column
	private Integer dealState;
	@Column
	private String dealSuggestion;
	@Column
	private Date dealTime;
	@Column
	private String dealResult;
	@Column
	private Date updateTime;
	@Column
	private String memo;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="dealperson")
	private User dealUser ;

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="complainant")
	private TigUsers complainUser ;
	
	public Complain()
	{
	}

	public Complain(String id)
	{
		this.id = id;
	}


	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getObjId()
	{
		return this.objId;
	}

	public void setObjId(String objId)
	{
		this.objId = objId;
	}

	public Integer getObjType()
	{
		return this.objType;
	}

	public void setObjType(Integer objType)
	{
		this.objType = objType;
	}

	public String getObjName()
	{
		return this.objName;
	}

	public void setObjName(String objName)
	{
		this.objName = objName;
	}

	public Date getComplainTime()
	{
		return this.complainTime;
	}

	public void setComplainTime(Date complainTime)
	{
		this.complainTime = complainTime;
	}

	public String getComplainReason()
	{
		return this.complainReason;
	}

	public void setComplainReason(String complainReason)
	{
		this.complainReason = complainReason;
	}

	public Integer getDealState()
	{
		return this.dealState;
	}

	public void setDealState(Integer dealState)
	{
		this.dealState = dealState;
	}

	public String getDealSuggestion()
	{
		return this.dealSuggestion;
	}

	public void setDealSuggestion(String dealSuggestion)
	{
		this.dealSuggestion = dealSuggestion;
	}

	public Date getDealTime()
	{
		return this.dealTime;
	}

	public void setDealTime(Date dealTime)
	{
		this.dealTime = dealTime;
	}

	public String getDealResult()
	{
		return this.dealResult;
	}

	public void setDealResult(String dealResult)
	{
		this.dealResult = dealResult;
	}

	public Date getUpdateTime()
	{
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime)
	{
		this.updateTime = updateTime;
	}

	public String getMemo()
	{
		return this.memo;
	}

	public void setMemo(String memo)
	{
		this.memo = memo;
	}

	public User getDealUser()
	{
		return dealUser;
	}

	public void setDealUser(User dealUser)
	{
		this.dealUser = dealUser;
	}

	public TigUsers getComplainUser()
	{
		return complainUser;
	}

	public void setComplainUser(TigUsers complainUser)
	{
		this.complainUser = complainUser;
	}

	@Override
	public String toString()
	{
		return "Complain [id=" + id + ", objId=" + objId + ", objType=" + objType + ", objName=" + objName + ", complainTime=" + complainTime + ", complainReason=" + complainReason + ", dealState="
				+ dealState + ", dealSuggestion=" + dealSuggestion + ", dealTime=" + dealTime + ", dealResult=" + dealResult + ", updateTime=" + updateTime + ", memo=" + memo + "]";
	}

}
