package com.hhxh.car.opr.domain;

// Generated 2015-9-2 14:29:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BaseHotWord generated by hbm2java
 */
@Entity
@Table(name="base_hot_word")
public class HotWord implements java.io.Serializable
{

	@Id
	@Column
	private String id;
	@Column
	private String name;
	@Column
	private Integer useState;
	@Column
	private Integer objType;
	@Column
	private Date updateTime;

	public HotWord()
	{
	}

	public HotWord(String id)
	{
		this.id = id;
	}

	public HotWord(String id, String name, Integer useState, Integer objType, Date updateTime)
	{
		this.id = id;
		this.name = name;
		this.useState = useState;
		this.objType = objType;
		this.updateTime = updateTime;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Integer getUseState()
	{
		return this.useState;
	}

	public void setUseState(Integer useState)
	{
		this.useState = useState;
	}

	public Integer getObjType()
	{
		return this.objType;
	}

	public void setObjType(Integer objType)
	{
		this.objType = objType;
	}

	public Date getUpdateTime()
	{
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime)
	{
		this.updateTime = updateTime;
	}

}
