package com.hhxh.car.sys.domain;

// Generated 2015-9-12 14:25:37 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hhxh.car.permission.domain.User;

/**
 * SysErrorLog generated by hbm2java
 */
@Entity
@Table(name = "sys_error_log")
public class ErrorLog implements java.io.Serializable
{
	@Id
	private String id;
	@Column
	private String operatorName;
	@Column
	private Date operationTime;
	@Column
	private Integer operationType;
	@Column
	private String exceptionMessage;
	@Column
	private String exceptionStackTrace;
	@Column
	private String actionPath ;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="OperatorID")
	private User operator ;

	public ErrorLog()
	{
	}

	public ErrorLog(String id)
	{
		this.id = id;
	}


	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}


	public String getOperatorName()
	{
		return this.operatorName;
	}

	public void setOperatorName(String operatorName)
	{
		this.operatorName = operatorName;
	}

	public Date getOperationTime()
	{
		return this.operationTime;
	}

	public void setOperationTime(Date operationTime)
	{
		this.operationTime = operationTime;
	}

	public Integer getOperationType()
	{
		return this.operationType;
	}

	public void setOperationType(Integer operationType)
	{
		this.operationType = operationType;
	}

	public String getExceptionMessage()
	{
		return this.exceptionMessage;
	}

	public void setExceptionMessage(String exceptionMessage)
	{
		this.exceptionMessage = exceptionMessage;
	}

	public User getOperator()
	{
		return operator;
	}

	public void setOperator(User operator)
	{
		this.operator = operator;
	}

	public String getExceptionStackTrace()
	{
		return exceptionStackTrace;
	}

	public void setExceptionStackTrace(String exceptionStackTrace)
	{
		this.exceptionStackTrace = exceptionStackTrace;
	}

	public String getActionPath()
	{
		return actionPath;
	}

	public void setActionPath(String actionPath)
	{
		this.actionPath = actionPath;
	}

}
