package com.hhxh.car.sys.domain;

// Generated 2015-9-11 15:52:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hhxh.car.permission.domain.User;

/**
 * SysLoginLog generated by hbm2java
 */
@Entity
@Table(name = "sys_login_log")
public class LoginLog implements java.io.Serializable
{
	@Id
	private String id;
	@Column
	private Date loginTime;
	@Column
	private Date exitTime;
	@Column
	private String ip;
	@Column
	private Integer port;
	@Column
	private String clientType;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="UserID")
	private User user ;

	public LoginLog()
	{
	}

	public LoginLog(String id)
	{
		this.id = id;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public Date getLoginTime()
	{
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime)
	{
		this.loginTime = loginTime;
	}

	public Date getExitTime()
	{
		return this.exitTime;
	}

	public void setExitTime(Date exitTime)
	{
		this.exitTime = exitTime;
	}

	public String getIp()
	{
		return this.ip;
	}

	public void setIp(String ip)
	{
		this.ip = ip;
	}

	public Integer getPort()
	{
		return this.port;
	}

	public void setPort(Integer port)
	{
		this.port = port;
	}

	public String getClientType()
	{
		return this.clientType;
	}

	public void setClientType(String clientType)
	{
		this.clientType = clientType;
	}

	public User getUser()
	{
		return user;
	}

	public void setUser(User user)
	{
		this.user = user;
	}

}
