package com.hhxh.car.sys.domain;

// Generated 2015-9-12 15:22:35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hhxh.car.permission.domain.User;

/**
 * SysOperatorLog generated by hbm2java 操作日志
 */
@Entity
@Table(name = "sys_operator_Log")
public class OperatorLog implements java.io.Serializable
{
	@Id
	private String id;
	@Column
	private String operatorName;
	@Column
	private Date operationTime;
	@Column
	private Integer operationType;
	@Column
	private String objId;
	@Column
	private String objName;
	@Column
	private String ip;
	@Column
	private Integer port;
	@Column
	private Long spendTime;
	@Column
	private String methodName ;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operatorId")
	private User operator;

	public OperatorLog()
	{
	}

	public OperatorLog(String id)
	{
		this.id = id;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getOperatorName()
	{
		return this.operatorName;
	}

	public void setOperatorName(String operatorName)
	{
		this.operatorName = operatorName;
	}

	public Date getOperationTime()
	{
		return this.operationTime;
	}

	public void setOperationTime(Date operationTime)
	{
		this.operationTime = operationTime;
	}

	public Integer getOperationType()
	{
		return this.operationType;
	}

	public void setOperationType(Integer operationType)
	{
		this.operationType = operationType;
	}

	public String getObjId()
	{
		return this.objId;
	}

	public void setObjId(String objId)
	{
		this.objId = objId;
	}

	public String getObjName()
	{
		return this.objName;
	}

	public void setObjName(String objName)
	{
		this.objName = objName;
	}

	public String getIp()
	{
		return this.ip;
	}

	public void setIp(String ip)
	{
		this.ip = ip;
	}

	public Integer getPort()
	{
		return this.port;
	}

	public void setPort(Integer port)
	{
		this.port = port;
	}

	public Long getSpendTime()
	{
		return this.spendTime;
	}

	public void setSpendTime(Long spendTime)
	{
		this.spendTime = spendTime;
	}

	public User getOperator()
	{
		return operator;
	}

	public void setOperator(User operator)
	{
		this.operator = operator;
	}

	public String getMethodName()
	{
		return methodName;
	}
	public void setMethodName(String methodName)
	{
		this.methodName = methodName;
	}
	
}
