package com.hhxh.car.base.car.domain;

// Generated 2015-9-1 18:12:18 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BaseCarName generated by hbm2java
 */
@Entity
@Table(name="base_car_name")
public class CarName implements java.io.Serializable
{

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Integer id;
	@Column(name="FIRST_LETTER")
	private String firstLetter;
	@Column(name="MAKE_NAME")
	private String makeName;
	@Column
	private Date updateTime;
	@Column
	private String photoUrl;

	public CarName()
	{
	}

	public CarName(String makeName)
	{
		this.makeName = makeName;
	}

	public CarName(String firstLetter, String makeName, Date updateTime, String photoUrl)
	{
		this.firstLetter = firstLetter;
		this.makeName = makeName;
		this.updateTime = updateTime;
		this.photoUrl = photoUrl;
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getFirstLetter()
	{
		return this.firstLetter;
	}

	public void setFirstLetter(String firstLetter)
	{
		this.firstLetter = firstLetter;
	}

	public String getMakeName()
	{
		return this.makeName;
	}

	public void setMakeName(String makeName)
	{
		this.makeName = makeName;
	}

	public Date getUpdateTime()
	{
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime)
	{
		this.updateTime = updateTime;
	}

	public String getPhotoUrl()
	{
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl)
	{
		this.photoUrl = photoUrl;
	}

}
