package com.hhxh.car.base.district.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.springframework.stereotype.Repository;

// Generated 2015-7-30 10:41:51 by Hibernate Tools 3.4.0.CR1

/**
 * BaseProvince generated by hbm2java
 */
@Entity
@Table(name="base_province")
public class BaseProvince implements java.io.Serializable {

	@Id
	@Column(name="provinceID")
	private String id;
	@Column
	private String code;
	@Column
	private String name;
	@Column
	private String sortCode;
	@Column
	private String memo;
	
	@OneToMany(fetch=FetchType.LAZY,mappedBy="baseProvince")
	@OrderBy("sortCode asc")
	private Set<BaseCity> baseCitys = new HashSet<BaseCity>();
	

	public BaseProvince() {
	}
	
	public BaseProvince(String id) {
		this.id = id;
	}


	public BaseProvince(String provinceId, String name) {
		this.id = provinceId;
		this.name = name;
	}

	public BaseProvince(String provinceId, String code, String name,
			String sortCode, String memo) {
		this.id = provinceId;
		this.code = code;
		this.name = name;
		this.sortCode = sortCode;
		this.memo = memo;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSortCode() {
		return this.sortCode;
	}

	public void setSortCode(String sortCode) {
		this.sortCode = sortCode;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Set<BaseCity> getBaseCitys() {
		return baseCitys;
	}

	public void setBaseCitys(Set<BaseCity> baseCitys) {
		this.baseCitys = baseCitys;
	}

	@Override
	public String toString() {
		return "BaseProvince [id=" + id + ", code=" + code + ", name=" + name
				+ ", sortCode=" + sortCode + ", memo=" + memo + ", baseCitys="
				 + "]";
	}

	
}
