package com.hhxh.car.base.district.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import org.springframework.stereotype.Repository;

// Generated 2015-7-30 10:41:51 by Hibernate Tools 3.4.0.CR1

/**
 * BaseCity generated by hbm2java
 */
@Entity
@Table(name="base_city")
public class BaseCity implements java.io.Serializable {

	@Id
	@Column(name="cityId")
	private String id;
	@Column
	private String cityCode;
	@Column
	private String cityName;
	@Column
	private String cellCode;
	@Column
	private Integer isHot;
	@Column
	private Integer isShow;
	@Column
	private String sortCode;
	@Column
	private String memo;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="provinceID")
	private BaseProvince baseProvince ;
	
	@OneToMany(fetch=FetchType.LAZY,mappedBy="baseCity")
	@OrderBy("sortCode asc")
	private Set<BaseArea> baseAreas = new HashSet<BaseArea>();
	

	public BaseCity() {
	}

	
	public BaseCity(String id) {
		super();
		this.id = id;
	}


	public BaseCity(String cityId, String cityName) {
		this.id = cityId;
		this.cityName = cityName;
	}

	public BaseCity(String cityId, String provinceId, String cityCode,
			String cityName, String cellCode, Integer isHot, Integer isShow,
			String sortCode, String memo) {
		this.id = cityId;
		this.cityCode = cityCode;
		this.cityName = cityName;
		this.cellCode = cellCode;
		this.isHot = isHot;
		this.isShow = isShow;
		this.sortCode = sortCode;
		this.memo = memo;
	}


	public String getCityCode() {
		return this.cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getCellCode() {
		return this.cellCode;
	}

	public void setCellCode(String cellCode) {
		this.cellCode = cellCode;
	}

	public Integer getIsHot() {
		return this.isHot;
	}

	public void setIsHot(Integer isHot) {
		this.isHot = isHot;
	}

	public Integer getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	public String getSortCode() {
		return this.sortCode;
	}

	public void setSortCode(String sortCode) {
		this.sortCode = sortCode;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}


	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public BaseProvince getBaseProvince() {
		return baseProvince;
	}


	public void setBaseProvince(BaseProvince baseProvince) {
		this.baseProvince = baseProvince;
	}


	public Set<BaseArea> getBaseAreas() {
		return baseAreas;
	}


	public void setBaseAreas(Set<BaseArea> baseAreas) {
		this.baseAreas = baseAreas;
	}


	@Override
	public String toString() {
		return "BaseCity [id=" + id + ", cityCode=" + cityCode + ", cityName="
				+ cityName + ", cellCode=" + cellCode + ", isHot=" + isHot
				+ ", isShow=" + isShow + ", sortCode=" + sortCode + ", memo="
				+ memo + ", baseProvince=" + baseProvince + ", baseAreas="
				 + "]";
	}
	
	

}
