package com.hhxh.car.base.busatom.domain;

// Generated 2015-7-11 11:34:31 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hhxh.car.base.autopart.domain.AutoPart;
import com.hhxh.car.base.busitem.domain.BusItem;

/**
 * BaseBusAtom generated by hbm2java
 * 
 * 利用了外键来进行约束，暂时只做了外键的约束，还有其他的约束没有做，包括外键的细节也没有进行处理
 */
@Entity
@Table(name="base_bus_atom")
public class BusAtom implements java.io.Serializable {

	@Id
	private String fid ;
	
	@Column(nullable=false,unique=true)
	private String atomCode;
	@Column
	private String atomName;

	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="itemCode")
	private BusItem busItem;
	@Column
	private Integer autoParts;

	@Column
	private BigDecimal eunitPrice;
	@Column
	private Date updateTime;
	@Column
	private String memo;
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="partId")
	private AutoPart autoPart ;

	public BusAtom() {
	}

	public BusAtom(String atomCode) {
		this.atomCode = atomCode;
	}

	public BusAtom(String atomCode, String atomName, String itemCode,
			Integer autoParts, BigDecimal eunitPrice,
			Date updateTime, String memo) {
		this.atomCode = atomCode;
		this.atomName = atomName;
		this.autoParts = autoParts;
		this.eunitPrice = eunitPrice;
		this.updateTime = updateTime;
		this.memo = memo;
	}

	public String getAtomCode() {
		return this.atomCode;
	}

	public void setAtomCode(String atomCode) {
		this.atomCode = atomCode;
	}

	public String getAtomName() {
		return this.atomName;
	}

	public void setAtomName(String atomName) {
		this.atomName = atomName;
	}


	public Integer getAutoParts() {
		return this.autoParts;
	}

	public void setAutoParts(Integer autoParts) {
		this.autoParts = autoParts;
	}


	public BigDecimal getEunitPrice() {
		return this.eunitPrice;
	}

	public void setEunitPrice(BigDecimal eunitPrice) {
		this.eunitPrice = eunitPrice;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public AutoPart getAutoPart() {
		return autoPart;
	}

	public void setAutoPart(AutoPart autoPart) {
		this.autoPart = autoPart;
	}

	public BusItem getBusItem() {
		return busItem;
	}

	public void setBusItem(BusItem busItem) {
		this.busItem = busItem;
	}

//	@Override
//	public String toString() {
//		return "BusAtom [atomCode=" + atomCode + ", atomName=" + atomName
//				+ ", busItem=" + busItem + ", autoParts=" + autoParts
//				+ ", eunitPrice=" + eunitPrice + ", updateTime=" + updateTime
//				+ ", memo=" + memo + ", autoPart=" + autoPart + "]";
//	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}


	
}
