package com.zw.test.domain.com.zw.test.domain;

// Generated 2015-8-7 19:44:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BaseBusPackageImg generated by hbm2java
 */
public class BusPackageImg implements java.io.Serializable
{

	private String id;
	private String packageId;
	private String content;
	private String fileType;
	private String fileName;
	private String filePath;
	private String serverIp;
	private Integer port;
	private String uploadUser;
	private Date uploadTime;

	public BusPackageImg()
	{
	}

	public BusPackageImg(String id, String packageId)
	{
		this.id = id;
		this.packageId = packageId;
	}

	public BusPackageImg(String id, String packageId, String content, String fileType, String fileName, String filePath, String serverIp, Integer port, String uploadUser, Date uploadTime)
	{
		this.id = id;
		this.packageId = packageId;
		this.content = content;
		this.fileType = fileType;
		this.fileName = fileName;
		this.filePath = filePath;
		this.serverIp = serverIp;
		this.port = port;
		this.uploadUser = uploadUser;
		this.uploadTime = uploadTime;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getPackageId()
	{
		return this.packageId;
	}

	public void setPackageId(String packageId)
	{
		this.packageId = packageId;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public String getFileType()
	{
		return this.fileType;
	}

	public void setFileType(String fileType)
	{
		this.fileType = fileType;
	}

	public String getFileName()
	{
		return this.fileName;
	}

	public void setFileName(String fileName)
	{
		this.fileName = fileName;
	}

	public String getFilePath()
	{
		return this.filePath;
	}

	public void setFilePath(String filePath)
	{
		this.filePath = filePath;
	}

	public String getServerIp()
	{
		return this.serverIp;
	}

	public void setServerIp(String serverIp)
	{
		this.serverIp = serverIp;
	}

	public Integer getPort()
	{
		return this.port;
	}

	public void setPort(Integer port)
	{
		this.port = port;
	}

	public String getUploadUser()
	{
		return this.uploadUser;
	}

	public void setUploadUser(String uploadUser)
	{
		this.uploadUser = uploadUser;
	}

	public Date getUploadTime()
	{
		return this.uploadTime;
	}

	public void setUploadTime(Date uploadTime)
	{
		this.uploadTime = uploadTime;
	}

}
