package com.hhxh.car.shop.domain;

// Generated 2015-7-13 16:10:35 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;

import com.hhxh.car.base.busatom.domain.BusAtom;
import com.hhxh.car.base.buspackage.domain.BusPackage;
import com.hhxh.car.base.carshop.domain.CarShop;

/**
 * BaseBusItem generated by hbm2java
 */
@Entity
@Table(name="opr_shop_item")
public class ShopItem implements java.io.Serializable {

	@Id
	@Column(name="itemId")
	private String fid ;
	
	@Column(nullable=false,unique=true)
	private String itemCode;
	@Column
	private String itemName;
	@Column
	private String itemDes;
	@Column
	private String photoUrl;
	@Column
	private BigDecimal standardPrice;
	@Column
	private BigDecimal actualPrice;
	@Column
	private BigDecimal workHours;
	@Column
	private BigDecimal autoPartsPrice;
	@Column
	private Integer useState;
	@Column
	private String useRule ;
	@Column
	private Integer isActivity;
	@Column
	private Date updateTime;
	@Column
	private String memo;
	@Column
	private Date starTime;
	@Column
	private Date endTime;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="shopID")
	private CarShop carShop ;
	
	
	@ManyToMany(mappedBy="shopItems",fetch=FetchType.LAZY)
	private Set<ShopPackage> shopPackages = new HashSet<ShopPackage>();
	
	@OneToMany(mappedBy="shopItem",fetch=FetchType.LAZY)
	private Set<ShopAtom> shopAtoms = new HashSet<ShopAtom>();
	
	@OneToMany(mappedBy="shopItem",fetch=FetchType.LAZY)
	private Set<ShopItemImg> shopItemImgs = new HashSet<ShopItemImg>();
	

	public ShopItem() {
	}

	public ShopItem(String fid) {
		this.fid = fid;
	}

	public ShopItem(String itemCode, String itemName, String itemDes,
			String photoUrl, BigDecimal standardPrice, BigDecimal actualPrice,
			BigDecimal workHours, BigDecimal autoPartsPrice, Integer useState,
			int isActivity, Date updateTime, String memo, Date starTime,
			Date endTime) {
		this.itemCode = itemCode;
		this.itemName = itemName;
		this.itemDes = itemDes;
		this.photoUrl = photoUrl;
		this.standardPrice = standardPrice;
		this.actualPrice = actualPrice;
		this.workHours = workHours;
		this.autoPartsPrice = autoPartsPrice;
		this.useState = useState;
		this.isActivity = isActivity;
		this.updateTime = updateTime;
		this.memo = memo;
		this.starTime = starTime;
		this.endTime = endTime;
	}

	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getItemDes() {
		return this.itemDes;
	}

	public void setItemDes(String itemDes) {
		this.itemDes = itemDes;
	}

	public String getPhotoUrl() {
		return this.photoUrl;
	}

	public void setPhotoUrl(String photoUrl) {
		this.photoUrl = photoUrl;
	}

	public BigDecimal getStandardPrice() {
		return this.standardPrice;
	}

	public void setStandardPrice(BigDecimal standardPrice) {
		this.standardPrice = standardPrice;
	}

	public BigDecimal getActualPrice() {
		return this.actualPrice;
	}

	public void setActualPrice(BigDecimal actualPrice) {
		this.actualPrice = actualPrice;
	}

	public BigDecimal getWorkHours() {
		return this.workHours;
	}

	public void setWorkHours(BigDecimal workHours) {
		this.workHours = workHours;
	}

	public BigDecimal getAutoPartsPrice() {
		return this.autoPartsPrice;
	}

	public void setAutoPartsPrice(BigDecimal autoPartsPrice) {
		this.autoPartsPrice = autoPartsPrice;
	}

	public Integer getUseState() {
		return this.useState;
	}

	public void setUseState(Integer useState) {
		this.useState = useState;
	}

	public Integer getIsActivity() {
		return this.isActivity;
	}

	public void setIsActivity(Integer isActivity) {
		this.isActivity = isActivity;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Date getStarTime() {
		return this.starTime;
	}

	public void setStarTime(Date starTime) {
		this.starTime = starTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}


	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}

	public Set<ShopPackage> getShopPackages() {
		return shopPackages;
	}

	public void setShopPackages(Set<ShopPackage> shopPackages) {
		this.shopPackages = shopPackages;
	}

	public Set<ShopAtom> getShopAtoms() {
		return shopAtoms;
	}

	public void setShopAtoms(Set<ShopAtom> shopAtoms) {
		this.shopAtoms = shopAtoms;
	}

	@Override
	public String toString() {
		return "BusItem [fid=" + fid + ", itemCode=" + itemCode + ", itemName="
				+ itemName + ", itemDes=" + itemDes + ", photoUrl=" + photoUrl
				+ ", standardPrice=" + standardPrice + ", actualPrice="
				+ actualPrice + ", workHours=" + workHours
				+ ", autoPartsPrice=" + autoPartsPrice + ", useState="
				+ useState + ", isActivity=" + isActivity + ", updateTime="
				+ updateTime + ", memo=" + memo + ", starTime=" + starTime;
	}

	public String getUseRule() {
		return useRule;
	}

	public void setUseRule(String useRule) {
		this.useRule = useRule;
	}

	public CarShop getCarShop() {
		return carShop;
	}

	public void setCarShop(CarShop carShop) {
		this.carShop = carShop;
	}

	public Set<ShopItemImg> getShopItemImgs() {
		return shopItemImgs;
	}

	public void setShopItemImgs(Set<ShopItemImg> shopItemImgs) {
		this.shopItemImgs = shopItemImgs;
	}
	
}
