package com.hhxh.car.shop.domain;

// Generated 2015-7-11 11:34:31 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.hhxh.car.base.autopart.domain.AutoPart;
import com.hhxh.car.base.busitem.domain.BusItem;
import com.hhxh.car.base.carshop.domain.CarShop;

/**
 * BaseBusAtom generated by hbm2java
 * 
 * 利用了外键来进行约束，暂时只做了外键的约束，还有其他的约束没有做，包括外键的细节也没有进行处理
 */
@Entity
@Table(name="opr_shop_atom")
public class ShopAtom implements java.io.Serializable {

	@Id
	@Column(name="atomID")
	private String fid ;
	
	@Column(nullable=false,unique=true)
	private String atomCode;
	
	@Column
	private String atomName;

	@Column
	private Integer autoParts;

	@Column
	private BigDecimal eunitPrice;
	@Column
	private Date updateTime;
	@Column
	private String memo;
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="partId")
	private AutoPart autoPart ;
	
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="itemID")
	private ShopItem shopItem;
	
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="shopId")
	private CarShop carShop ;

	public ShopAtom() {
	}

	public ShopAtom(String atomCode) {
		this.atomCode = atomCode;
	}

	public ShopAtom(String atomCode, String atomName, String itemCode,
			Integer autoParts, BigDecimal eunitPrice,
			Date updateTime, String memo) {
		this.atomCode = atomCode;
		this.atomName = atomName;
		this.autoParts = autoParts;
		this.eunitPrice = eunitPrice;
		this.updateTime = updateTime;
		this.memo = memo;
	}

	public String getAtomCode() {
		return this.atomCode;
	}

	public void setAtomCode(String atomCode) {
		this.atomCode = atomCode;
	}

	public String getAtomName() {
		return this.atomName;
	}

	public void setAtomName(String atomName) {
		this.atomName = atomName;
	}


	public Integer getAutoParts() {
		return this.autoParts;
	}

	public void setAutoParts(Integer autoParts) {
		this.autoParts = autoParts;
	}


	public BigDecimal getEunitPrice() {
		return this.eunitPrice;
	}

	public void setEunitPrice(BigDecimal eunitPrice) {
		this.eunitPrice = eunitPrice;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public AutoPart getAutoPart() {
		return autoPart;
	}

	public void setAutoPart(AutoPart autoPart) {
		this.autoPart = autoPart;
	}

	public ShopItem getShopItem() {
		return shopItem;
	}

	public void setShopItem(ShopItem shopItem) {
		this.shopItem = shopItem;
	}

	public CarShop getCarShop() {
		return carShop;
	}

	public void setCarShop(CarShop carShop) {
		this.carShop = carShop;
	}

	public String getFid() {
		return fid;
	}

	public void setFid(String fid) {
		this.fid = fid;
	}


	
}
